var cards = [

{	name:		"Ace of Clubs",
	weight:		11,
	image_file_name:	"clubs_ace.svg",
	tag:		"clubs_ace",
	suit:		"clubs"
			
},
{	name:		"Two of Clubs",
	weight:		2,
	image_file_name:	"clubs_2.svg",
	tag:		"clubs_2",
	suit:		"clubs"
			
},
{	name:		"Three of Clubs",
	weight:		3,
	image_file_name:	"clubs_3.svg",
	tag:		"clubs_3",
	suit:		"clubs"
},
{	name:		"Four of Clubs",
	weight:		4,
	image_file_name:	"clubs_4.svg",
	tag:		"clubs_4",
	suit:		"clubs"
},
{	name:		"Five of Clubs",
	weight:		5,
	image_file_name:	"clubs_5.svg",
	tag:		"clubs_5",
	suit:		"clubs"
},
{	name:		"Six of Clubs",
	weight:		6,
	image_file_name:	"clubs_6.svg",
	tag:		"clubs_6",
	suit:		"clubs"
},
{	name:		"Seven of Clubs",
	weight:		7,
	image_file_name:	"clubs_7.svg",
	tag:		"clubs_7",
	suit:		"clubs"
},
{	name:		"Eight of Clubs",
	weight:		8,
	image_file_name:	"clubs_8.svg",
	tag:		"clubs_8",
	suit:		"clubs"
},
{	name:		"Nine of Clubs",
	weight:		9,
	image_file_name:	"clubs_9.svg",
	tag:		"clubs_9",
	suit:		"clubs"
},
{	name:		"Ten of Clubs",
	weight:		10,
	image_file_name:	"clubs_10.svg",
	tag:		"clubs_10",
	suit:		"clubs"
},
{	name:		"Jack of Clubs",
	weight:		10,
	image_file_name:	"clubs_jack.svg",
	tag:		"clubs_jack",
	suit:		"clubs"
},
{	name:		"Queen of Clubs",
	weight:		10,
	image_file_name:	"clubs_queen.svg",
	tag:		"clubs_queen",
	suit:		"clubs"
},
{	name:		"King of Clubs",
	weight:		10,
	image_file_name:	"clubs_king.svg",
	tag:		"clubs_king",
	suit:		"clubs"
},
{	name:		"Ace of Diamonds",
	weight:		11,
	image_file_name:	"diamonds_ace.svg",
	tag:		"diamonds_ace",
	suit:		"diamonds"
},
{	name:		"Two of Diamonds",
	weight:		2,
	image_file_name:	"diamonds_2.svg",
	tag:		"diamonds_2",
	suit:		"diamonds"
},
{	name:		"Three of Diamonds",
	weight:		3,
	image_file_name:	"diamonds_3.svg",
	tag:		"diamonds_3",
	suit:		"diamonds"
},
{	name:		"Four of Diamonds",
	weight:		4,
	image_file_name:	"diamonds_4.svg",
	tag:		"diamonds_4",
	suit:		"diamonds"
},
{	name:		"Five of Diamonds",
	weight:		5,
	image_file_name:	"diamonds_5.svg",
	tag:		"diamonds_5",
	suit:		"diamonds"
},
{	name:		"Six of Diamonds",
	weight:		6,
	image_file_name:	"diamonds_6.svg",
	tag:		"diamonds_6",
	suit:		"diamonds"
},
{	name:		"Seven of Diamonds",
	weight:		7,
	image_file_name:	"diamonds_7.svg",
	tag:		"diamonds_7",
	suit:		"diamonds"
},
{	name:		"Eight of Diamonds",
	weight:		8,
	image_file_name:	"diamonds_8.svg",
	tag:		"diamonds_8",
	suit:		"diamonds"
},
{	name:		"Nine of Diamonds",
	weight:		9,
	image_file_name:	"diamonds_9.svg",
	tag:		"diamonds_9",
	suit:		"diamonds"
},
{	name:		"Ten of Diamonds",
	weight:		10,
	image_file_name:	"diamonds_10.svg",
	tag:		"diamonds_10",
	suit:		"diamonds"
},
{	name:		"Jack of Diamonds",
	weight:		10,
	image_file_name:	"diamonds_jack.svg",
	tag:		"diamonds_jack",
	suit:		"diamonds"
},
{	name:		"Queen of Diamonds",
	weight:		10,
	image_file_name:	"diamonds_queen.svg",
	tag:		"diamonds_queen",
	suit:		"diamonds"
},
{	name:		"King of Diamonds",
	weight:		10,
	image_file_name:	"diamonds_king.svg",
	tag:		"diamonds_king",
	suit:		"diamonds"
},
{	name:		"Ace of Spades",
	weight:		11,
	image_file_name:	"spades_ace.svg",
	tag:		"spades_ace",
	suit:		"spades"
},
{	name:		"Two of Spades",
	weight:		2,
	image_file_name:	"spades_2.svg",
	tag:		"spades_2",
	suit:		"spades"
},
{	name:		"Three of Spades",
	weight:		3,
	image_file_name:	"spades_3.svg",
	tag:		"spades_3",
	suit:		"spades"
},
{	name:		"Four of Spades",
	weight:		4,
	image_file_name:	"spades_4.svg",
	tag:		"spades_4",
	suit:		"spades"
},
{	name:		"Five of Spades",
	weight:		5,
	image_file_name:	"spades_5.svg",
	tag:		"spades_5",
	suit:		"spades"
},
{	name:		"Six of Spades",
	weight:		6,
	image_file_name:	"spades_6.svg",
	tag:		"spades_6",
	suit:		"spades"
},
{	name:		"Seven of Spades",
	weight:		7,
	image_file_name:	"spades_7.svg",
	tag:		"spades_7",
	suit:		"spades"
},
{	name:		"Eight of Spades",
	weight:		8,
	image_file_name:	"spades_8.svg",
	tag:		"spades_8",
	suit:		"spades" 
},
{	name:		"Nine of Spades",
	weight:		9,
	image_file_name:	"spades_9.svg",
	tag:		"spades_9",
	suit:		"spades"
},
{	name:		"Ten of Spades",
	weight:		10,
	image_file_name:	"spades_10.svg",
	tag:		"spades_10",
	suit:		"spades"
},
{	name:		"Jack of Spades",
	weight:		10,
	image_file_name:	"spades_jack.svg",
	tag:		"spades_jack",
	suit:		"spades"
},
{	name:		"Queen of Spades",
	weight:		10,
	image_file_name:	"spades_queen.svg",
	tag:		"spades_queen",
	suit:		"spades"
},
{	name:		"King of Spades",
	weight:		10,
	image_file_name:	"spades_king.svg",
	tag:		"spades_king",
	suit:		"spades"
},
{	name:		"Ace of Hearts",
	weight:		11,
	image_file_name:	"hearts_ace.svg",
	tag:		"hearts_ace",
	suit:		"hearts"
},
{	name:		"Two of Hearts",
	weight:		2,
	image_file_name:	"hearts_2.svg",
	tag:		"hearts_2",
	suit:		"hearts"
},
{	name:		"Three of Hearts",
	weight:		3,
	image_file_name:	"hearts_3.svg",
	tag:		"hearts_3",
	suit:		"hearts"
},
{	name:		"Four of Hearts",
	weight:		4,
	image_file_name:	"hearts_4.svg",
	tag:		"hearts_4",
	suit:		"hearts"
},
{	name:		"Five of Hearts",
	weight:		5,
	image_file_name:	"hearts_5.svg",
	tag:		"hearts_5",
	suit:		"hearts"
},
{	name:		"Six of Hearts",
	weight:		6,
	image_file_name:	"hearts_6.svg",
	tag:		"hearts_6",
	suit:		"hearts"
},
{	name:		"Seven of Hearts",
	weight:		7,
	image_file_name:	"hearts_7.svg",
	tag:		"hearts_7",
	suit:		"hearts"
},
{	name:		"Eight of Hearts",
	weight:		8,
	image_file_name:	"hearts_8.svg",
	tag:		"hearts_8",
	suit:		"hearts"
},
{	name:		"Nine of Hearts",
	weight:		9,
	image_file_name:	"hearts_9.svg",
	tag:		"hearts_9",
	suit:		"hearts"
},
{	name:		"Ten of Hearts",
	weight:		10,
	image_file_name:	"hearts_10.svg",
	tag:		"hearts_10",
	suit:		"hearts"
},
{	name:		"Jack of Hearts",
	weight:		10,
	image_file_name:	"hearts_jack.svg",
	tag:		"hearts_jack",
	suit:		"hearts"
},
{	name:		"Queen of Hearts",
	weight:		10,
	image_file_name:	"hearts_queen.svg",
	tag:		"hearts_queen",
	suit:		"hearts"
},
{	name:		"King of Hearts",
	weight:		10,
	image_file_name:	"hearts_king.svg",
	tag:		"hearts_king",
	suit:		"hearts"
}


];